mixed-port: 7890
allow-lan: true
bind-address: '*'
mode: rule
log-level: info
unified-delay: true
external-controller: '127.0.0.1:9090'
dns:
    enable: true
    listen: '0.0.0.0:53'
    use-hosts: true
    ipv6: true
    enhanced-mode: fake-ip
    fake-ip-range: 28.0.0.1/8
    fake-ip-filter: ['*', +.lan, +.local]
    default-nameserver: [223.5.5.5]
    nameserver: ['https://dns.alidns.com/dns-query', 'https://1.12.12.12/dns-query']
    proxy-server-nameserver: ['https://doh.pub/dns-query', 'https://1.12.12.12/dns-query']
    direct-nameserver: ['https://dns.alidns.com/dns-query', 'https://1.12.12.12/dns-query']
geox-url:
    geoip: 'https://ghpr.de/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat'
    geosite: 'https://ghpr.de/https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat'
sniffer:
    enable: false
    sniff: { TLS: { ports: [443, 8443] }, HTTP: { ports: [80, 8080-8880], override-destination: true } }
    skip-domain: ['Mijia Cloud', dlg.io.mi.com, +.apple.com]
    force-domain: [google.com]